### ISSUE TITLE
Execute: floating point rounding assertion error

### ISSUE THREAD

**Issue by w3dkramer** [konveyor/tackle-test-generator-cli#58]
**Describe the bug**

Tests may throw an AssertionFailedError when comparing floating point numbers due to rounding.

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

- If the failure occurred for the `execute` command, please attach the zip file of the directory
  containing the generated test JUnit test cases
[junit-reports.zip](https://github.com/konveyor/tackle-test-generator-cli/files/6975610/junit-reports.zip)

<img width="1282" alt="Screen Shot 2021-08-12 at 08 29 34" src="https://user-images.githubusercontent.com/32372921/129196823-42fe1da8-42de-47f4-ad85-255007bae7e0.png">

**Environment information**

 - CLI version: commit 19f8aa1199aa8dddff95032e2addb3b9d63d46ef
 - OS: macOS

**Comment by rachelt44** [comment]
@w3dkramer I looked into this issue. It turns out that Randoop API which we are using for executing the test cases (while generating them, for recording of results) is rounding/cutting these float values, so the subsequent digits are lost when recording results. This will be challenging to fix in a third-party tool. Currently we require a delta of at most `0.0001` between recorded values and values created during test execution. We can relax this requirement but running the risk of missing floating point computation bugs. Will be happy to hear your view on this trade-off.

**Comment by w3dkramer** [comment]
@rachelt44 Is it practical to change the delta specifically for tests executed with the Randoop API? Since the API seems to be cutting off or rounding after two decimal points, perhaps setting a delta of `0.01` (or `0.005`) would make this executor compatible with it, without any noticeable ill effect.  
I do not want to jeopardize the accuracy of the executor, but for this case for the TMF app the exact floating point rounding accuracy of this library file does not matter, so I am content with a relaxed requirement that allows the tests to pass. For this app this may be a moot issue since this the assertion errors are all raised from a file of an entire library we wish to exclude from test generation/execution if feature #59 is implemented.
If something changes to make it easier later on, enforcing the current requirement with both the expected and actual values would be terrific, but for now I would be happy if either the delta can be relaxed or we can exclude this file.

**Comment by rachelt44** [comment]
@w3dkramer thank you Daniel, this is very helpful. For now I refined the delta to `0.015`. To obtain the fix you need to re-download the tackle-test-generator-core jar. We'll also handle soon the feature request you posted in #59.
