### ISSUE TITLE
Coverage-driven test augmentation 

### ISSUE THREAD

**Issue by sinha108** [konveyor/tackle-test-generator-cli#70]
**Is your feature request related to a problem? Please describe.**

Implement an option for ctd-amplified test generation in which the generated test suite is augmented with tests from the base tests generated by evosuite that increase the code coverage achieved by the CTD test suite. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rachelt44** [comment]
The base test suite on which augmentation is performed should be determined by the coverage efficiency (coverage divided by number of test methods) of ctd-amplified and evosuite test suites. The test suite with the higher coverage efficiency is used as the base test suite. The other one is used to add tests to the base test suite for coverage augmentation.

Since this is implemented entirely in the cli, we can use simple regex matching to determine the number of test methods generated by evosuite.
