### ISSUE TITLE
Use dependencies from Maven Central repositories (or similars)

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#91]
**Is your feature request related to a problem? Please describe.**

It should not be a requirement to build locally `tkltest` command to have a GitHub repo with a personal token. It is not a good starting point for a new user. Most of the users could have a GitHub account, but not all of them could have.

If Maven is one of the building components to package the tool, then it should use dependencies availables from [Maven Central Repository](https://repo1.maven.org/maven2/) or other Maven repositories common in the Open Source ecosystem ([Red Hat](https://maven.repository.redhat.com/ga/), [Sonatype](https://oss.sonatype.org/content/repositories/releases/), ...).

If you don't have those credentials then you are not able to build the tool. The following exception appears:

```shell
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.560 s
[INFO] Finished at: 2021-10-11T15:13:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tackle-test-generator-cli: Could not resolve dependencies for project org.konveyor:tackle-test-generator-cli:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.konveyor:tackle-test-generator-core:jar:1.0.0-SNAPSHOT: Failed to read artifact descriptor for org.konveyor:tackle-test-generator-core:jar:1.0.0-SNAPSHOT: Could not transfer artifact org.konveyor:tackle-test-generator-core:pom:1.0.0-SNAPSHOT from/to github (https://maven.pkg.github.com/konveyor/tackle-test-generator-core): authentication failed for https://maven.pkg.github.com/konveyor/tackle-test-generator-core/org/konveyor/tackle-test-generator-core/1.0.0-SNAPSHOT/tackle-test-generator-core-1.0.0-SNAPSHOT.pom, status: 401 Unauthorized -> [Help 1]
```

**Describe the solution you'd like**

Allow to build the tool using the standard lifecycles based in Maven and avoid to have custom scripts, or custom credentials to build locally the tool.

**Describe alternatives you've considered**

Locate and use any dependency needed using Maven GAV coordinates from Maven Central (or similar) repositories.

**Comment by sinha108** [comment]
@rmarting: For the Java library dependencies of TackleTest, the ones that are available in Maven Central are in fact downloaded from there. It's only for the dependencies that are not available in Maven Central that we download versions that are hosted elsewhere:

1. Randoop jar downloaded from https://github.com/randoop/randoop/releases/
2. EvoSuite jars (for a specific code build that is not an EvoSuite release) downloaded from https://github.com/sinha108?tab=packages&repo_name=maven-packages
3. TackleTest-core jar downloaded from Konveyor GitHub Packages Maven repository: https://github.com/orgs/konveyor/packages?repo_name=tackle-test-generator-core

A GitHub PAT is required for downloading (3), without which the build failure you mentioned occurs. However, we now have workarounds for that with
- TackleTest releases that include all dependencies (archive files with `*-all-deps` in their names): https://github.com/konveyor/tackle-test-generator-cli/releases
- Prebuilt TackleTest container images published in GitHub container registry: https://github.com/konveyor/tackle-test-generator-cli/pkgs/container/tackle-test-generator-cli

So TackleTest users no longer need to set up a GitHub PAT in order to use the tool. If this sounds OK to you, perhaps this issue can be closed?

Thanks

**Comment by sinha108** [comment]
All dependencies are now specified on via Maven Central or Jitpack. GitHub PAT is no longer needed for installing TackleTest or for running the GitHub Actions workflows.
